const testData = [{
    code: "01a",
    available: true,
    type: "suite",
    bedrooms: 2,
    basePrice: 750,
    size: 51,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: true,
    secure: true,
    image: '01',
    description: "Aquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    code: "02a",
    available: true,
    type: "studio",
    bedrooms: 1,
    basePrice: 550,
    size: 24,
    storage: true,
    bathroom: true,
    customColors: false,
    customMods: true,
    secure: true,
    image: '02',
    description: "Arcu risus quis varius quam quisque id. Amet porttitor eget dolor morbi non arcu risus. Porttitor leo a diam sollicitudin tempor id. Tempus urna et pharetra pharetra massa massa ultricies. Ultricies tristique nulla aliquet enim tortor at auctor urna. Viverra ipsum nunc aliquet bibendum enim facilisis gravida.",
  },
  {
    code: "03a",
    available: false,
    type: "suite",
    bedrooms: 2,
    basePrice: 650,
    size: 34,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: true,
    image: '03',
    description: "Tincidunt augue interdum velit euismod in pellentesque. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Augue lacus viverra vitae tincidunt augue interdum velit euismod.",
  },
  {
    code: "04b",
    available: true,
    type: "suite",
    bedrooms: 2,
    basePrice: 700,
    size: 36,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: true,
    secure: true,
    image: '01',
    description: "Dolor morbi non arcu risus. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Quam viverra orci sagittis eu volutpat. In eu mi bibendum neque egestas. Lectus quam id leo in vitae. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel.",
  },
  {
    code: "05b",
    available: false,
    type: "studio",
    bedrooms: 1,
    basePrice: 600,
    size: 28,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: false,
    image: '02',
    description: "Quis varius quam quisque id. Elit scelerisque mauris pellentesque pulvinar pellentesque. Enim tortor at auctor urna nunc. Eu sem integer vitae justo eget magna. Nunc sed id semper risus in hendrerit gravida. Sodales ut eu sem integer vitae justo. Vivamus arcu felis bibendum.",
  },
  {
    code: "06b",
    available: true,
    type: "studio",
    bedrooms: 1,
    basePrice: 650,
    size: 28,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: true,
    secure: true,
    image: '03',
    description: "Aquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    code: "11c",
    available: true,
    type: "suite",
    bedrooms: 2,
    basePrice: 750,
    size: 37,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: false,
    image: '01',
    description: "Tincidunt augue interdum velit euismod in pellentesque. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Augue lacus viverra vitae tincidunt augue interdum velit euismod.",
  },
  {
    code: "12c",
    available: true,
    type: "suite",
    bedrooms: 3,
    basePrice: 900,
    size: 48,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: true,
    secure: false,
    image: '02',
    description: "Amet volutpat consequat mauris nunc congue nisi. Eu facilisis sed odio morbi quis commodo odio. Quam lacus suspendisse faucibus interdum posuere. Orci porta non pulvinar neque laoreet suspendisse interdum. Mauris augue neque gravida in fermentum et sollicitudin.",
  },
  {
    code: "13c",
    available: false,
    type: "suite",
    bedrooms: 3,
    basePrice: 900,
    size: 57,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: true,
    secure: false,
    image: '03',
    description: "Tincidunt augue interdum velit euismod in pellentesque. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Augue lacus viverra vitae tincidunt augue interdum velit euismod.",
  },
  {
    code: "14b",
    available: false,
    type: "suite",
    bedrooms: 3,
    basePrice: 950,
    size: 51,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: true,
    image: '01',
    description: "Aquis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    code: "15b",
    available: true,
    type: "suite",
    bedrooms: 2,
    basePrice: 800,
    size: 51,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: true,
    image: '02',
    description: "Arcu risus quis varius quam quisque id. Amet porttitor eget dolor morbi non arcu risus. Porttitor leo a diam sollicitudin tempor id. Tempus urna et pharetra pharetra massa massa ultricies. Ultricies tristique nulla aliquet enim tortor at auctor urna. Viverra ipsum nunc aliquet bibendum enim facilisis gravida.",
  },
  {
    code: "15c",
    available: true,
    type: "studio",
    bedrooms: 1,
    basePrice: 650,
    size: 33,
    storage: true,
    bathroom: true,
    customColors: true,
    customMods: false,
    secure: false,
    image: '03',
    description: "Quis varius quam quisque id. Elit scelerisque mauris pellentesque pulvinar pellentesque. Enim tortor at auctor urna nunc. Eu sem integer vitae justo eget magna. Nunc sed id semper risus in hendrerit gravida. Sodales ut eu sem integer vitae justo. Vivamus arcu felis bibendum.",
  },
];

const perkValues = {
  furnishing: 80,
  billing: 50
}

export {
  testData,
  perkValues
}